declare module "lucide-react" {
  import type { FC, SVGProps } from "react"

  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: number | string
    color?: string
    strokeWidth?: number | string
  }

  // Navigation & UI Icons
  export const Search: FC<IconProps>
  export const Share2: FC<IconProps>
  export const Clock: FC<IconProps>
  export const Code: FC<IconProps>
  export const Star: FC<IconProps>
  export const ExternalLink: FC<IconProps>
  export const Github: FC<IconProps>
  export const Filter: FC<IconProps>
  export const ArrowLeft: FC<IconProps>
  export const ArrowRight: FC<IconProps>
  export const Menu: FC<IconProps>
  export const X: FC<IconProps>
  export const ChevronDown: FC<IconProps>
  export const ChevronUp: FC<IconProps>
  export const ChevronLeft: FC<IconProps>
  export const ChevronRight: FC<IconProps>
  export const MoreHorizontal: FC<IconProps>
  export const Plus: FC<IconProps>
  export const Minus: FC<IconProps>
  export const Check: FC<IconProps>
  export const CheckCircle: FC<IconProps>
  export const AlertCircle: FC<IconProps>
  export const Info: FC<IconProps>
  export const HelpCircle: FC<IconProps>
  export const Settings: FC<IconProps>
  export const User: FC<IconProps>
  export const Users: FC<IconProps>
  export const Home: FC<IconProps>
  export const BookOpen: FC<IconProps>
  export const Brain: FC<IconProps>
  export const Trophy: FC<IconProps>
  export const Target: FC<IconProps>
  export const Zap: FC<IconProps>
  export const Lightbulb: FC<IconProps>
  export const Rocket: FC<IconProps>
  export const Globe: FC<IconProps>
  export const Mail: FC<IconProps>
  export const Phone: FC<IconProps>
  export const MapPin: FC<IconProps>
  export const Calendar: FC<IconProps>
  export const Clock3: FC<IconProps>
  export const Timer: FC<IconProps>
  export const Play: FC<IconProps>
  export const Pause: FC<IconProps>
  export const Stop: FC<IconProps>
  export const SkipForward: FC<IconProps>
  export const SkipBack: FC<IconProps>
  export const Volume2: FC<IconProps>
  export const VolumeX: FC<IconProps>
  export const Mic: FC<IconProps>
  export const MicOff: FC<IconProps>
  export const Camera: FC<IconProps>
  export const Image: FC<IconProps>
  export const Video: FC<IconProps>
  export const FileText: FC<IconProps>
  export const File: FC<IconProps>
  export const Folder: FC<IconProps>
  export const Download: FC<IconProps>
  export const Upload: FC<IconProps>
  export const Link: FC<IconProps>
  export const Copy: FC<IconProps>
  export const Clipboard: FC<IconProps>
  export const Edit: FC<IconProps>
  export const Edit2: FC<IconProps>
  export const Trash: FC<IconProps>
  export const Trash2: FC<IconProps>
  export const Save: FC<IconProps>
  export const RefreshCw: FC<IconProps>
  export const RotateCcw: FC<IconProps>
  export const Undo: FC<IconProps>
  export const Redo: FC<IconProps>
  export const Eye: FC<IconProps>
  export const EyeOff: FC<IconProps>
  export const Lock: FC<IconProps>
  export const Unlock: FC<IconProps>
  export const Shield: FC<IconProps>
  export const Key: FC<IconProps>
  export const LogIn: FC<IconProps>
  export const LogOut: FC<IconProps>
  export const UserPlus: FC<IconProps>
  export const UserMinus: FC<IconProps>
  export const Heart: FC<IconProps>
  export const HeartHandshake: FC<IconProps>
  export const ThumbsUp: FC<IconProps>
  export const ThumbsDown: FC<IconProps>
  export const MessageCircle: FC<IconProps>
  export const MessageSquare: FC<IconProps>
  export const Send: FC<IconProps>
  export const Bell: FC<IconProps>
  export const BellOff: FC<IconProps>
  export const Bookmark: FC<IconProps>
  export const BookmarkPlus: FC<IconProps>
  export const Flag: FC<IconProps>
  export const Tag: FC<IconProps>
  export const Hash: FC<IconProps>
  export const AtSign: FC<IconProps>
  export const Percent: FC<IconProps>
  export const DollarSign: FC<IconProps>
  export const CreditCard: FC<IconProps>
  export const ShoppingCart: FC<IconProps>
  export const ShoppingBag: FC<IconProps>
  export const Package: FC<IconProps>
  export const Truck: FC<IconProps>
  export const Car: FC<IconProps>
  export const Plane: FC<IconProps>
  export const Train: FC<IconProps>
  export const Bike: FC<IconProps>
  export const Walk: FC<IconProps>
  export const Navigation: FC<IconProps>
  export const Compass: FC<IconProps>
  export const Map: FC<IconProps>
  export const Layers: FC<IconProps>
  export const Grid: FC<IconProps>
  export const List: FC<IconProps>
  export const BarChart: FC<IconProps>
  export const BarChart2: FC<IconProps>
  export const BarChart3: FC<IconProps>
  export const LineChart: FC<IconProps>
  export const PieChart: FC<IconProps>
  export const TrendingUp: FC<IconProps>
  export const TrendingDown: FC<IconProps>
  export const Activity: FC<IconProps>
  export const Wifi: FC<IconProps>
  export const WifiOff: FC<IconProps>
  export const Bluetooth: FC<IconProps>
  export const Battery: FC<IconProps>
  export const BatteryLow: FC<IconProps>
  export const Signal: FC<IconProps>
  export const Smartphone: FC<IconProps>
  export const Tablet: FC<IconProps>
  export const Laptop: FC<IconProps>
  export const Monitor: FC<IconProps>
  export const Tv: FC<IconProps>
  export const Speaker: FC<IconProps>
  export const Headphones: FC<IconProps>
  export const Mouse: FC<IconProps>
  export const Keyboard: FC<IconProps>
  export const Printer: FC<IconProps>
  export const Scanner: FC<IconProps>
  export const HardDrive: FC<IconProps>
  export const Database: FC<IconProps>
  export const Server: FC<IconProps>
  export const Cloud: FC<IconProps>
  export const CloudDownload: FC<IconProps>
  export const CloudUpload: FC<IconProps>
  export const CloudOff: FC<IconProps>
  export const Loader: FC<IconProps>
  export const Loader2: FC<IconProps>
  export const MoreVertical: FC<IconProps>
  export const Maximize: FC<IconProps>
  export const Minimize: FC<IconProps>
  export const Maximize2: FC<IconProps>
  export const Minimize2: FC<IconProps>
  export const Move: FC<IconProps>
  export const RotateCw: FC<IconProps>
  export const ZoomIn: FC<IconProps>
  export const ZoomOut: FC<IconProps>
  export const Focus: FC<IconProps>
  export const Crosshair: FC<IconProps>
  export const Target2: FC<IconProps>
  export const Aperture: FC<IconProps>
  export const Sun: FC<IconProps>
  export const Moon: FC<IconProps>
  export const Stars: FC<IconProps>
  export const Cloud2: FC<IconProps>
  export const CloudRain: FC<IconProps>
  export const CloudSnow: FC<IconProps>
  export const CloudLightning: FC<IconProps>
  export const Thermometer: FC<IconProps>
  export const Droplets: FC<IconProps>
  export const Wind: FC<IconProps>
  export const Umbrella: FC<IconProps>
  export const Snowflake: FC<IconProps>
  export const Flame: FC<IconProps>
  export const Waves: FC<IconProps>
  export const Mountain: FC<IconProps>
  export const Trees: FC<IconProps>
  export const Flower: FC<IconProps>
  export const Leaf: FC<IconProps>
  export const Sprout: FC<IconProps>
  export const Bug: FC<IconProps>
  export const Fish: FC<IconProps>
  export const Bird: FC<IconProps>
  export const Cat: FC<IconProps>
  export const Dog: FC<IconProps>
  export const Rabbit: FC<IconProps>
  export const Turtle: FC<IconProps>
  export const Coffee: FC<IconProps>
  export const Cup: FC<IconProps>
  export const Wine: FC<IconProps>
  export const Beer: FC<IconProps>
  export const Pizza: FC<IconProps>
  export const Cake: FC<IconProps>
  export const Apple: FC<IconProps>
  export const Cherry: FC<IconProps>
  export const Grape: FC<IconProps>
  export const Banana: FC<IconProps>
  export const Carrot: FC<IconProps>
  export const Salad: FC<IconProps>
  export const Utensils: FC<IconProps>
  export const UtensilsCrossed: FC<IconProps>
  export const ChefHat: FC<IconProps>
  export const Cookie: FC<IconProps>
  export const IceCream: FC<IconProps>
  export const Candy: FC<IconProps>
  export const Gift: FC<IconProps>
  export const GiftCard: FC<IconProps>
  export const PartyPopper: FC<IconProps>
  export const Balloon: FC<IconProps>
  export const Cake2: FC<IconProps>
  export const Crown: FC<IconProps>
  export const Award: FC<IconProps>
  export const Medal: FC<IconProps>
  export const Badge: FC<IconProps>
  export const Gem: FC<IconProps>
  export const Diamond: FC<IconProps>
  export const Coins: FC<IconProps>
  export const Banknote: FC<IconProps>
  export const Wallet: FC<IconProps>
  export const PiggyBank: FC<IconProps>
  export const Calculator: FC<IconProps>
  export const Receipt: FC<IconProps>
  export const Building: FC<IconProps>
  export const Building2: FC<IconProps>
  export const Store: FC<IconProps>
  export const Warehouse: FC<IconProps>
  export const Factory: FC<IconProps>
  export const School: FC<IconProps>
  export const GraduationCap: FC<IconProps>
  export const Library: FC<IconProps>
  export const Hospital: FC<IconProps>
  export const Stethoscope: FC<IconProps>
  export const Pill: FC<IconProps>
  export const Syringe: FC<IconProps>
  export const Bandage: FC<IconProps>
  export const HeartPulse: FC<IconProps>
  export const Activity2: FC<IconProps>
  export const Dumbbell: FC<IconProps>
  export const Bike2: FC<IconProps>
  export const Football: FC<IconProps>
  export const Basketball: FC<IconProps>
  export const Tennis: FC<IconProps>
  export const Golf: FC<IconProps>
  export const Volleyball: FC<IconProps>
  export const Gamepad: FC<IconProps>
  export const Gamepad2: FC<IconProps>
  export const Joystick: FC<IconProps>
  export const Dice1: FC<IconProps>
  export const Dice2: FC<IconProps>
  export const Dice3: FC<IconProps>
  export const Dice4: FC<IconProps>
  export const Dice5: FC<IconProps>
  export const Dice6: FC<IconProps>
  export const Spade: FC<IconProps>
  export const Club: FC<IconProps>
  export const Heart2: FC<IconProps>
  export const Diamond2: FC<IconProps>
  export const Music: FC<IconProps>
  export const Music2: FC<IconProps>
  export const Music3: FC<IconProps>
  export const Music4: FC<IconProps>
  export const Radio: FC<IconProps>
  export const Disc: FC<IconProps>
  export const Disc2: FC<IconProps>
  export const Disc3: FC<IconProps>
  export const Headphones2: FC<IconProps>
  export const Mic2: FC<IconProps>
  export const MicVocal: FC<IconProps>
  export const Piano: FC<IconProps>
  export const Guitar: FC<IconProps>
  export const Drum: FC<IconProps>
  export const Violin: FC<IconProps>
  export const Trumpet: FC<IconProps>
  export const Saxophone: FC<IconProps>
  export const Palette: FC<IconProps>
  export const Paintbrush: FC<IconProps>
  export const Paintbrush2: FC<IconProps>
  export const Brush: FC<IconProps>
  export const Pen: FC<IconProps>
  export const PenTool: FC<IconProps>
  export const Pencil: FC<IconProps>
  export const Eraser: FC<IconProps>
  export const Ruler: FC<IconProps>
  export const Triangle: FC<IconProps>
  export const Square: FC<IconProps>
  export const Circle: FC<IconProps>
  export const Hexagon: FC<IconProps>
  export const Pentagon: FC<IconProps>
  export const Octagon: FC<IconProps>
  export const Shapes: FC<IconProps>
  export const Box: FC<IconProps>
  export const Package2: FC<IconProps>
  export const Archive: FC<IconProps>
  export const Inbox: FC<IconProps>
  export const Outbox: FC<IconProps>
  export const FolderOpen: FC<IconProps>
  export const FolderPlus: FC<IconProps>
  export const FolderMinus: FC<IconProps>
  export const FolderX: FC<IconProps>
  export const Files: FC<IconProps>
  export const FileImage: FC<IconProps>
  export const FileVideo: FC<IconProps>
  export const FileAudio: FC<IconProps>
  export const FilePdf: FC<IconProps>
  export const FileSpreadsheet: FC<IconProps>
  export const FileCode: FC<IconProps>
  export const FileJson: FC<IconProps>
  export const FileX: FC<IconProps>
  export const FilePlus: FC<IconProps>
  export const FileMinus: FC<IconProps>
  export const FileEdit: FC<IconProps>
  export const FileSearch: FC<IconProps>
  export const FileCheck: FC<IconProps>
  export const FileWarning: FC<IconProps>
  export const FileQuestion: FC<IconProps>
  export const ScanLine: FC<IconProps>
  export const QrCode: FC<IconProps>
  export const Barcode: FC<IconProps>
  export const Fingerprint: FC<IconProps>
  export const Scan: FC<IconProps>
  export const ScanFace: FC<IconProps>
  export const ScanEye: FC<IconProps>
  export const Webcam: FC<IconProps>
  export const CameraOff: FC<IconProps>
  export const VideoOff: FC<IconProps>
  export const Film: FC<IconProps>
  export const Clapperboard: FC<IconProps>
  export const PlayCircle: FC<IconProps>
  export const PauseCircle: FC<IconProps>
  export const StopCircle: FC<IconProps>
  export const Record: FC<IconProps>
  export const FastForward: FC<IconProps>
  export const Rewind: FC<IconProps>
  export const Repeat: FC<IconProps>
  export const Repeat1: FC<IconProps>
  export const Shuffle: FC<IconProps>
  export const SkipForward2: FC<IconProps>
  export const SkipBack2: FC<IconProps>
  export const StepForward: FC<IconProps>
  export const StepBack: FC<IconProps>
  export const ChevronsLeft: FC<IconProps>
  export const ChevronsRight: FC<IconProps>
  export const ChevronsUp: FC<IconProps>
  export const ChevronsDown: FC<IconProps>
  export const ChevronsUpDown: FC<IconProps>
  export const ChevronsLeftRight: FC<IconProps>
  export const ArrowUp: FC<IconProps>
  export const ArrowDown: FC<IconProps>
  export const ArrowUpRight: FC<IconProps>
  export const ArrowDownRight: FC<IconProps>
  export const ArrowUpLeft: FC<IconProps>
  export const ArrowDownLeft: FC<IconProps>
  export const ArrowBigUp: FC<IconProps>
  export const ArrowBigDown: FC<IconProps>
  export const ArrowBigLeft: FC<IconProps>
  export const ArrowBigRight: FC<IconProps>
  export const ArrowUpCircle: FC<IconProps>
  export const ArrowDownCircle: FC<IconProps>
  export const ArrowLeftCircle: FC<IconProps>
  export const ArrowRightCircle: FC<IconProps>
  export const ArrowUpSquare: FC<IconProps>
  export const ArrowDownSquare: FC<IconProps>
  export const ArrowLeftSquare: FC<IconProps>
  export const ArrowRightSquare: FC<IconProps>
  export const MoveUp: FC<IconProps>
  export const MoveDown: FC<IconProps>
  export const MoveLeft: FC<IconProps>
  export const MoveRight: FC<IconProps>
  export const MoveUpRight: FC<IconProps>
  export const MoveDownRight: FC<IconProps>
  export const MoveUpLeft: FC<IconProps>
  export const MoveDownLeft: FC<IconProps>
  export const MoveDiagonal: FC<IconProps>
  export const MoveDiagonal2: FC<IconProps>
  export const MoveHorizontal: FC<IconProps>
  export const MoveVertical: FC<IconProps>
  export const Move3d: FC<IconProps>
  export const Expand: FC<IconProps>
  export const Shrink: FC<IconProps>
  export const FlipHorizontal: FC<IconProps>
  export const FlipVertical: FC<IconProps>
  export const FlipHorizontal2: FC<IconProps>
  export const FlipVertical2: FC<IconProps>
  export const RotateCcw2: FC<IconProps>
  export const RotateCw2: FC<IconProps>
  export const Rotate3d: FC<IconProps>
  export const Scale: FC<IconProps>
  export const Scale3d: FC<IconProps>
  export const Scaling: FC<IconProps>
  export const ScanText: FC<IconProps>
  export const ScanSearch: FC<IconProps>
  export const SearchX: FC<IconProps>
  export const SearchCheck: FC<IconProps>
  export const SearchCode: FC<IconProps>
  export const SearchSlash: FC<IconProps>
  export const Locate: FC<IconProps>
  export const LocateFixed: FC<IconProps>
  export const LocateOff: FC<IconProps>
  export const Navigation2: FC<IconProps>
  export const NavigationOff: FC<IconProps>
  export const Anchor: FC<IconProps>
  export const Ship: FC<IconProps>
  export const Sailboat: FC<IconProps>
  export const Plane2: FC<IconProps>
  export const PlaneTakeoff: FC<IconProps>
  export const PlaneLanding: FC<IconProps>
  export const Helicopter: FC<IconProps>
  export const Rocket2: FC<IconProps>
  export const Satellite: FC<IconProps>
  export const Orbit: FC<IconProps>
  export const Globe2: FC<IconProps>
  export const Earth: FC<IconProps>
  export const Moon2: FC<IconProps>
  export const Sun2: FC<IconProps>
  export const Sunrise: FC<IconProps>
  export const Sunset: FC<IconProps>
  export const Eclipse: FC<IconProps>
  export const Telescope: FC<IconProps>
  export const Microscope: FC<IconProps>
  export const Atom: FC<IconProps>
  export const Dna: FC<IconProps>
  export const Beaker: FC<IconProps>
  export const TestTube: FC<IconProps>
  export const FlaskConical: FC<IconProps>
  export const FlaskRound: FC<IconProps>
  export const Magnet: FC<IconProps>
  export const Zap2: FC<IconProps>
  export const Bolt: FC<IconProps>
  export const BatteryCharging: FC<IconProps>
  export const Plug: FC<IconProps>
  export const Plug2: FC<IconProps>
  export const PlugZap: FC<IconProps>
  export const Power: FC<IconProps>
  export const PowerOff: FC<IconProps>
  export const ToggleLeft: FC<IconProps>
  export const ToggleRight: FC<IconProps>
  export const SwitchCamera: FC<IconProps>
  export const Repeat2: FC<IconProps>
  export const RefreshCcw: FC<IconProps>
  export const RefreshCw2: FC<IconProps>
  export const RotateCounterClockwise: FC<IconProps>
  export const RotateClockwise: FC<IconProps>
  export const Timer2: FC<IconProps>
  export const TimerOff: FC<IconProps>
  export const TimerReset: FC<IconProps>
  export const Stopwatch: FC<IconProps>
  export const Hourglass: FC<IconProps>
  export const AlarmClock: FC<IconProps>
  export const AlarmClockOff: FC<IconProps>
  export const Clock4: FC<IconProps>
  export const Clock8: FC<IconProps>
  export const Clock12: FC<IconProps>
  export const WatchIcon: FC<IconProps>
  export const CalendarDays: FC<IconProps>
  export const CalendarCheck: FC<IconProps>
  export const CalendarX: FC<IconProps>
  export const CalendarPlus: FC<IconProps>
  export const CalendarMinus: FC<IconProps>
  export const CalendarClock: FC<IconProps>
  export const CalendarHeart: FC<IconProps>
  export const CalendarRange: FC<IconProps>
  export const CalendarSearch: FC<IconProps>
  export const Date: FC<IconProps>
  export const History: FC<IconProps>
  export const Archive2: FC<IconProps>
  export const ArchiveRestore: FC<IconProps>
  export const ArchiveX: FC<IconProps>
  export const Bookmark2: FC<IconProps>
  export const BookmarkMinus: FC<IconProps>
  export const BookmarkX: FC<IconProps>
  export const BookmarkCheck: FC<IconProps>
  export const Book: FC<IconProps>
  export const BookOpen2: FC<IconProps>
  export const BookMarked: FC<IconProps>
  export const BookCopy: FC<IconProps>
  export const BookPlus: FC<IconProps>
  export const BookMinus: FC<IconProps>
  export const BookX: FC<IconProps>
  export const BookCheck: FC<IconProps>
  export const BookHeart: FC<IconProps>
  export const BookKey: FC<IconProps>
  export const BookLock: FC<IconProps>
  export const BookUser: FC<IconProps>
  export const Notebook: FC<IconProps>
  export const NotebookPen: FC<IconProps>
  export const NotebookTabs: FC<IconProps>
  export const StickyNote: FC<IconProps>
  export const Quote: FC<IconProps>
  export const Type: FC<IconProps>
  export const Heading: FC<IconProps>
  export const Heading1: FC<IconProps>
  export const Heading2: FC<IconProps>
  export const Heading3: FC<IconProps>
  export const Heading4: FC<IconProps>
  export const Heading5: FC<IconProps>
  export const Heading6: FC<IconProps>
  export const Paragraph: FC<IconProps>
  export const Text: FC<IconProps>
  export const TextCursor: FC<IconProps>
  export const TextCursorInput: FC<IconProps>
  export const TextSelect: FC<IconProps>
  export const TextQuote: FC<IconProps>
  export const TextSearch: FC<IconProps>
  export const Strikethrough: FC<IconProps>
  export const Underline: FC<IconProps>
  export const Italic: FC<IconProps>
  export const Bold: FC<IconProps>
  export const Subscript: FC<IconProps>
  export const Superscript: FC<IconProps>
  export const CaseSensitive: FC<IconProps>
  export const CaseUpper: FC<IconProps>
  export const CaseLower: FC<IconProps>
  export const WrapText: FC<IconProps>
  export const AlignLeft: FC<IconProps>
  export const AlignCenter: FC<IconProps>
  export const AlignRight: FC<IconProps>
  export const AlignJustify: FC<IconProps>
  export const AlignStartVertical: FC<IconProps>
  export const AlignCenterVertical: FC<IconProps>
  export const AlignEndVertical: FC<IconProps>
  export const AlignStartHorizontal: FC<IconProps>
  export const AlignCenterHorizontal: FC<IconProps>
  export const AlignEndHorizontal: FC<IconProps>
  export const DistributeHorizontal: FC<IconProps>
  export const DistributeVertical: FC<IconProps>
  export const SpaceBetweenHorizontal: FC<IconProps>
  export const SpaceBetweenVertical: FC<IconProps>
  export const Indent: FC<IconProps>
  export const Outdent: FC<IconProps>
  export const IndentIncrease: FC<IconProps>
  export const IndentDecrease: FC<IconProps>
  export const ListOrdered: FC<IconProps>
  export const ListUnordered: FC<IconProps>
  export const ListChecks: FC<IconProps>
  export const ListTodo: FC<IconProps>
  export const ListX: FC<IconProps>
  export const ListPlus: FC<IconProps>
  export const ListMinus: FC<IconProps>
  export const ListStart: FC<IconProps>
  export const ListEnd: FC<IconProps>
  export const ListRestart: FC<IconProps>
  export const ListCollapse: FC<IconProps>
  export const ListTree: FC<IconProps>
  export const ListFilter: FC<IconProps>
  export const Table: FC<IconProps>
  export const Table2: FC<IconProps>
  export const TableProperties: FC<IconProps>
  export const Columns: FC<IconProps>
  export const Columns2: FC<IconProps>
  export const Columns3: FC<IconProps>
  export const Columns4: FC<IconProps>
  export const Rows: FC<IconProps>
  export const Rows2: FC<IconProps>
  export const Rows3: FC<IconProps>
  export const Rows4: FC<IconProps>
  export const Grid2x2: FC<IconProps>
  export const Grid3x3: FC<IconProps>
  export const LayoutGrid: FC<IconProps>
  export const LayoutList: FC<IconProps>
  export const LayoutDashboard: FC<IconProps>
  export const LayoutTemplate: FC<IconProps>
  export const LayoutPanelLeft: FC<IconProps>
  export const LayoutPanelRight: FC<IconProps>
  export const LayoutPanelTop: FC<IconProps>
  export const LayoutPanelBottom: FC<IconProps>
  export const Sidebar: FC<IconProps>
  export const SidebarOpen: FC<IconProps>
  export const SidebarClose: FC<IconProps>
  export const PanelLeft: FC<IconProps>
  export const PanelRight: FC<IconProps>
  export const PanelTop: FC<IconProps>
  export const PanelBottom: FC<IconProps>
  export const PanelLeftOpen: FC<IconProps>
  export const PanelLeftClose: FC<IconProps>
  export const PanelRightOpen: FC<IconProps>
  export const PanelRightClose: FC<IconProps>
  export const PanelTopOpen: FC<IconProps>
  export const PanelTopClose: FC<IconProps>
  export const PanelBottomOpen: FC<IconProps>
  export const PanelBottomClose: FC<IconProps>
  export const SeparatorHorizontal: FC<IconProps>
  export const SeparatorVertical: FC<IconProps>
  export const Split: FC<IconProps>
  export const SplitSquareHorizontal: FC<IconProps>
  export const SplitSquareVertical: FC<IconProps>
  export const Combine: FC<IconProps>
  export const UnfoldHorizontal: FC<IconProps>
  export const UnfoldVertical: FC<IconProps>
  export const FoldHorizontal: FC<IconProps>
  export const FoldVertical: FC<IconProps>
  export const Workflow: FC<IconProps>
  export const GitBranch: FC<IconProps>
  export const GitCommit: FC<IconProps>
  export const GitMerge: FC<IconProps>
  export const GitPullRequest: FC<IconProps>
  export const GitPullRequestDraft: FC<IconProps>
  export const GitPullRequestClosed: FC<IconProps>
  export const GitFork: FC<IconProps>
  export const GitCompare: FC<IconProps>
  export const GitGraph: FC<IconProps>
  export const Terminal: FC<IconProps>
  export const TerminalSquare: FC<IconProps>
  export const Command: FC<IconProps>
  export const Cpu: FC<IconProps>
  export const MemoryStick: FC<IconProps>
  export const HardDriveDownload: FC<IconProps>
  export const HardDriveUpload: FC<IconProps>
  export const ScanBarcode: FC<IconProps>
  export const Binary: FC<IconProps>
  export const Braces: FC<IconProps>
  export const Brackets: FC<IconProps>
  export const Parentheses: FC<IconProps>
  export const Regex: FC<IconProps>
  export const Variable: FC<IconProps>
  export const Function: FC<IconProps>
  export const Component: FC<IconProps>
  export const Package3: FC<IconProps>
  export const Puzzle: FC<IconProps>
  export const Plugin: FC<IconProps>
  export const Extension: FC<IconProps>
  export const Api: FC<IconProps>
  export const Webhook: FC<IconProps>
  export const Rss: FC<IconProps>
  export const Wifi2: FC<IconProps>
  export const WifiHigh: FC<IconProps>
  export const WifiLow: FC<IconProps>
  export const WifiZero: FC<IconProps>
  export const Ethernet: FC<IconProps>
  export const Router: FC<IconProps>
  export const Antenna: FC<IconProps>
  export const Radio2: FC<IconProps>
  export const Satellite2: FC<IconProps>
  export const Tower: FC<IconProps>
  export const Radar: FC<IconProps>
  export const Sonar: FC<IconProps>
  export const Cast: FC<IconProps>
  export const Airplay: FC<IconProps>
  export const Chromecast: FC<IconProps>
  export const Tv2: FC<IconProps>
  export const MonitorSpeaker: FC<IconProps>
  export const MonitorX: FC<IconProps>
  export const MonitorOff: FC<IconProps>
  export const MonitorCheck: FC<IconProps>
  export const MonitorPlay: FC<IconProps>
  export const MonitorPause: FC<IconProps>
  export const MonitorStop: FC<IconProps>
  export const MonitorDot: FC<IconProps>
  export const ScreenShare: FC<IconProps>
  export const ScreenShareOff: FC<IconProps>
  export const Presentation: FC<IconProps>
  export const Projector: FC<IconProps>
  export const Slideshow: FC<IconProps>
  export const Image2: FC<IconProps>
  export const ImageOff: FC<IconProps>
  export const ImagePlus: FC<IconProps>
  export const ImageMinus: FC<IconProps>
  export const ImageDown: FC<IconProps>
  export const ImageUp: FC<IconProps>
  export const Images: FC<IconProps>
  export const Gallery: FC<IconProps>
  export const GalleryHorizontal: FC<IconProps>
  export const GalleryVertical: FC<IconProps>
  export const GalleryHorizontalEnd: FC<IconProps>
  export const GalleryVerticalEnd: FC<IconProps>
  export const GalleryThumbnails: FC<IconProps>
  export const Crop: FC<IconProps>
  export const CropRotate: FC<IconProps>
  export const Scissors: FC<IconProps>
  export const ScissorsLineDashed: FC<IconProps>
  export const ScissorsSquare: FC<IconProps>
  export const ScissorsSquareDashedBottom: FC<IconProps>
  export const Slice: FC<IconProps>
  export const RectangleHorizontal: FC<IconProps>
  export const RectangleVertical: FC<IconProps>
  export const RectangleEllipsis: FC<IconProps>
  export const SquareActivity: FC<IconProps>
  export const SquareArrowDown: FC<IconProps>
  export const SquareArrowLeft: FC<IconProps>
  export const SquareArrowRight: FC<IconProps>
  export const SquareArrowUp: FC<IconProps>
  export const SquareArrowOutDownLeft: FC<IconProps>
  export const SquareArrowOutDownRight: FC<IconProps>
  export const SquareArrowOutUpLeft: FC<IconProps>
  export const SquareArrowOutUpRight: FC<IconProps>
  export const SquareAsterisk: FC<IconProps>
  export const SquareCheck: FC<IconProps>
  export const SquareCheckBig: FC<IconProps>
  export const SquareChevronDown: FC<IconProps>
  export const SquareChevronLeft: FC<IconProps>
  export const SquareChevronRight: FC<IconProps>
  export const SquareChevronUp: FC<IconProps>
  export const SquareCode: FC<IconProps>
  export const SquareDashedBottom: FC<IconProps>
  export const SquareDashedBottomCode: FC<IconProps>
  export const SquareDashedKanban: FC<IconProps>
  export const SquareDashedMousePointer: FC<IconProps>
  export const SquareDivide: FC<IconProps>
  export const SquareDot: FC<IconProps>
  export const SquareEqual: FC<IconProps>
  export const SquareFunction: FC<IconProps>
  export const SquareGanttChart: FC<IconProps>
  export const SquareKanban: FC<IconProps>
  export const SquareLibrary: FC<IconProps>
  export const SquareM: FC<IconProps>
  export const SquareMenu: FC<IconProps>
  export const SquareMinus: FC<IconProps>
  export const SquareMousePointer: FC<IconProps>
  export const SquareParking: FC<IconProps>
  export const SquareParking2: FC<IconProps>
  export const SquarePen: FC<IconProps>
  export const SquarePercent: FC<IconProps>
  export const SquarePi: FC<IconProps>
  export const SquarePilcrow: FC<IconProps>
  export const SquarePlay: FC<IconProps>
  export const SquarePlus: FC<IconProps>
  export const SquarePower: FC<IconProps>
  export const SquareRadical: FC<IconProps>
  export const SquareScissors: FC<IconProps>
  export const SquareSigma: FC<IconProps>
  export const SquareSlash: FC<IconProps>
  export const SquareSplitHorizontal: FC<IconProps>
  export const SquareSplitVertical: FC<IconProps>
  export const SquareStack: FC<IconProps>
  export const SquareTerminal: FC<IconProps>
  export const SquareUser: FC<IconProps>
  export const SquareUserRound: FC<IconProps>
  export const SquareX: FC<IconProps>
  export const CircleActivity: FC<IconProps>
  export const CircleAlert: FC<IconProps>
  export const CircleArrowDown: FC<IconProps>
  export const CircleArrowLeft: FC<IconProps>
  export const CircleArrowRight: FC<IconProps>
  export const CircleArrowUp: FC<IconProps>
  export const CircleArrowOutDownLeft: FC<IconProps>
  export const CircleArrowOutDownRight: FC<IconProps>
  export const CircleArrowOutUpLeft: FC<IconProps>
  export const CircleArrowOutUpRight: FC<IconProps>
  export const CircleCheckBig: FC<IconProps>
  export const CircleChevronDown: FC<IconProps>
  export const CircleChevronLeft: FC<IconProps>
  export const CircleChevronRight: FC<IconProps>
  export const CircleChevronUp: FC<IconProps>
  export const CircleDashed: FC<IconProps>
  export const CircleDivide: FC<IconProps>
  export const CircleDollarSign: FC<IconProps>
  export const CircleDot: FC<IconProps>
  export const CircleDotDashed: FC<IconProps>
  export const CircleEllipsis: FC<IconProps>
  export const CircleEqual: FC<IconProps>
  export const CircleFadingPlus: FC<IconProps>
  export const CircleGauge: FC<IconProps>
  export const CircleHelp: FC<IconProps>
  export const CircleMinus: FC<IconProps>
  export const CircleOff: FC<IconProps>
  export const CircleParking: FC<IconProps>
  export const CircleParkingOff: FC<IconProps>
  export const CirclePause: FC<IconProps>
  export const CirclePercent: FC<IconProps>
  export const CirclePlus: FC<IconProps>
  export const CirclePower: FC<IconProps>
  export const CircleSlash: FC<IconProps>
  export const CircleSlash2: FC<IconProps>
  export const CircleStop: FC<IconProps>
  export const CircleUser: FC<IconProps>
  export const CircleUserRound: FC<IconProps>
  export const CircleX: FC<IconProps>
  export const Disc4: FC<IconProps>
  export const DiscAlbum: FC<IconProps>
  export const Donut: FC<IconProps>
  export const Dot: FC<IconProps>
  export const DotSquare: FC<IconProps>
  export const Ellipsis: FC<IconProps>
  export const EllipsisVertical: FC<IconProps>
  export const Equal: FC<IconProps>
  export const EqualNot: FC<IconProps>
  export const Minus2: FC<IconProps>
  export const Plus2: FC<IconProps>
  export const Divide: FC<IconProps>
  export const Multiply: FC<IconProps>
  export const Sigma: FC<IconProps>
  export const Pi: FC<IconProps>
  export const Infinity: FC<IconProps>
  export const Radical: FC<IconProps>
  export const Superscript2: FC<IconProps>
  export const Subscript2: FC<IconProps>
  export const SquareRoot: FC<IconProps>
  export const FunctionSquare: FC<IconProps>
  export const Variable2: FC<IconProps>
  export const Sigma2: FC<IconProps>
  export const Pi2: FC<IconProps>
  export const Infinity2: FC<IconProps>
  export const Integral: FC<IconProps>
  export const Derivative: FC<IconProps>
  export const Limit: FC<IconProps>
  export const Sum: FC<IconProps>
  export const Product: FC<IconProps>
  export const Union: FC<IconProps>
  export const Intersection: FC<IconProps>
  export const Subset: FC<IconProps>
  export const Superset: FC<IconProps>
  export const Element: FC<IconProps>
  export const NotElement: FC<IconProps>
  export const EmptySet: FC<IconProps>
  export const Universal: FC<IconProps>
  export const Existential: FC<IconProps>
  export const Negation: FC<IconProps>
  export const Conjunction: FC<IconProps>
  export const Disjunction: FC<IconProps>
  export const Implication: FC<IconProps>
  export const Equivalence: FC<IconProps>
  export const Therefore: FC<IconProps>
  export const Because: FC<IconProps>
  export const Proportional: FC<IconProps>
  export const Approximately: FC<IconProps>
  export const NotEqual: FC<IconProps>
  export const LessEqual: FC<IconProps>
  export const GreaterEqual: FC<IconProps>
  export const Much: FC<IconProps>
  export const MuchLess: FC<IconProps>
  export const MuchGreater: FC<IconProps>
  export const PlusMinus: FC<IconProps>
  export const MinusPlus: FC<IconProps>
  export const Times: FC<IconProps>
  export const Oplus: FC<IconProps>
  export const Ominus: FC<IconProps>
  export const Otimes: FC<IconProps>
  export const Oslash: FC<IconProps>
  export const Odot: FC<IconProps>
  export const Bullet: FC<IconProps>
  export const Asterisk: FC<IconProps>
  export const Dagger: FC<IconProps>
  export const DoubleDagger: FC<IconProps>
  export const Section: FC<IconProps>
  export const Paragraph2: FC<IconProps>
  export const Pilcrow: FC<IconProps>
  export const Copyright: FC<IconProps>
  export const Registered: FC<IconProps>
  export const Trademark: FC<IconProps>
  export const Degree: FC<IconProps>
  export const Celsius: FC<IconProps>
  export const Fahrenheit: FC<IconProps>
  export const Kelvin: FC<IconProps>
  export const Ohm: FC<IconProps>
  export const Micro: FC<IconProps>
  export const Mho: FC<IconProps>
  export const Angstrom: FC<IconProps>
  export const Alpha: FC<IconProps>
  export const Beta: FC<IconProps>
  export const Gamma: FC<IconProps>
  export const Delta: FC<IconProps>
  export const Epsilon: FC<IconProps>
  export const Zeta: FC<IconProps>
  export const Eta: FC<IconProps>
  export const Theta: FC<IconProps>
  export const Iota: FC<IconProps>
  export const Kappa: FC<IconProps>
  export const Lambda: FC<IconProps>
  export const Mu: FC<IconProps>
  export const Nu: FC<IconProps>
  export const Xi: FC<IconProps>
  export const Omicron: FC<IconProps>
  export const Rho: FC<IconProps>
  export const Tau: FC<IconProps>
  export const Upsilon: FC<IconProps>
  export const Phi: FC<IconProps>
  export const Chi: FC<IconProps>
  export const Psi: FC<IconProps>
  export const Omega: FC<IconProps>
}
